"""Add aimodel table

Revision ID: 886fdf4ccfbd
Revises: a63d7ee6d246
Create Date: 2024-06-19 23:29:42.861644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '886fdf4ccfbd'
down_revision = 'a63d7ee6d246'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aimodel',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('mean_squared_error', sa.Float(), nullable=False),
    sa.Column('mean_absolute_error', sa.Float(), nullable=False),
    sa.Column('r2_score', sa.Float(), nullable=False),
    sa.Column('model_type', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('aimodel')
    # ### end Alembic commands ###
