"""empty message

Revision ID: a63d7ee6d246
Revises: 96cfd9b47f53
Create Date: 2024-05-31 14:59:52.161215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a63d7ee6d246'
down_revision = '96cfd9b47f53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cinemadata',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('day', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('visitors', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cinemadata')
    # ### end Alembic commands ###
